apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "donetick.fullname" . }}-config
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
data:
  {{ .Values.config.name }}.yaml: |-
{{ tpl (toYaml .Values.config) . | indent 4 }}
