apiVersion: v2
name: papra
description: A Helm chart for Papra, a minimalistic document archiving platform
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "26.6.1"

annotations:
  values-schema: https://raw.githubusercontent.com/brahmlower/helm-charts/refs/tags/papra-0.1.0/charts/papra/values.schema.json

home: https://papra.app
sources:
  - https://github.com/papra-hq/papra
  - https://github.com/rintaun/homelab-charts/tree/main/charts/papra
keywords:
  - document-management
  - paperless
