name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install helm-values plugin
        run: helm plugin install https://github.com/brahmlower/helm-values/releases/download/0.4.1/values-0.4.1.tgz --verify=false

      - name: Run lint and template checks
        run: task test

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build chart dependencies
        run: task deps

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
          packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
