name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install helm-values plugin
        run: helm plugin install https://github.com/brahmlower/helm-values/releases/download/0.4.0/values-0.4.0.tgz --verify=false

      - name: Run lint and template checks
        run: task test
